#!/usr/bin/env ruby

require 'yaml'
require 'logger'
require_relative 'validator'
require_relative 'git-util'

if ARGV.size != 1
	puts "Git multi mirror utility"
	puts "Copyright 2016 Dario Lombardo"
	puts "\nUsage: #{File.basename($0)} <conf file>\n\n"
	exit 1
end

conf = YAML.load_file(ARGV.first)

logger = Logger.new(conf['logfile'] || STDOUT)
logger.info("Starting")

conf['projects'].each do |project|
	if !validate_project(project)
		logger.info("Invalid Project, discarding")
		logger.debug("Project: #{project.inspect}")
		next
	end

	g = setup_working_dir(project, logger)
	pull_push(g, logger)
end
